// Mocks generated by Mockito 5.4.6 from annotations
// in phf/test/presentation/pages/settings/backup_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:phf/logic/services/interfaces/security_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ISecurityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISecurityService extends _i1.Mock implements _i2.ISecurityService {
  MockISecurityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setPin, [pin]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> validatePin(String? inputPin) =>
      (super.noSuchMethod(
            Invocation.method(#validatePin, [inputPin]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> changePin(String? oldPin, String? newPin) =>
      (super.noSuchMethod(
            Invocation.method(#changePin, [oldPin, newPin]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canCheckBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#canCheckBiometrics, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> enableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#enableBiometrics, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> disableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#disableBiometrics, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isBiometricsEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricsEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasLock() =>
      (super.noSuchMethod(
            Invocation.method(#hasLock, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
